version: '3.8'

services:
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_new
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # 🔥 IMPORTANT
    restart: always

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube_new
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    restart: always

volumes:
  jenkins_home: